/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Home_Panorama.glb -o Panorama.js 
*/

import React, { useRef,useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Panorama(props) {
  const [lightColors, setLightColors] = useState({
    Light_bedroom: 'blue',
    Light_garden: 'blue',
    Light_garage: 'blue',
    Light1_kitchen: 'blue',
    Light2_kitchen:'blue',
    Light_livingroom:'blue',
    Light2_livingroom:'blue',
    Light_bathroom:'blue'
    
    // Add more lights and their default colors here
  });
  const { nodes, materials } = useGLTF('/Home_Panorama.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[12.184, 12.184, 9.722]}>
        <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
        <mesh geometry={nodes.Plane_1.geometry} material={nodes.Plane_1.material} />
        <mesh geometry={nodes.Plane_2.geometry} material={nodes.Plane_2.material} />
        <mesh geometry={nodes.Plane_3.geometry} material={nodes.Plane_3.material} />
      </group>
      <mesh geometry={nodes.Bedroom_1.geometry} material={nodes.Bedroom_1.material} position={[0, 0.022, 0]} scale={[12.184, 12.184, 9.722]} >
        <meshStandardMaterial color='brown' />
      </mesh> 
      <mesh geometry={nodes.Living_Room.geometry} material={nodes.Living_Room.material} position={[0, 0.042, 0]} scale={[12.184, 12.184, 9.722]} >
        <meshStandardMaterial color='brown' />
      </mesh> 
      <mesh geometry={nodes.Bathroom_1.geometry} material={nodes.Bathroom_1.material} position={[0, 0.025, 0]} scale={[12.184, 12.184, 9.722]} >
        <meshStandardMaterial color='brown' />
      </mesh> 
      <mesh geometry={nodes.Kitchen.geometry} material={nodes.Kitchen.material} position={[0, 0.015, 0]} scale={[12.184, 12.184, 9.722]} >
        <meshStandardMaterial color='brown' />
      </mesh> 
      <mesh geometry={nodes.Garage.geometry} material={nodes.Garage.material} position={[0, 0.007, 0]} scale={[12.184, 12.184, 9.722]} >
        <meshStandardMaterial color='brown' />
      </mesh> 
      <mesh geometry={nodes.Garden.geometry} material={nodes.Garden.material} position={[0, 0.009, 0]} scale={[12.184, 12.184, 9.722]} >
        <meshStandardMaterial color='darkgreen' />
      </mesh> 
      <mesh geometry={nodes.Light_garage.geometry} material={nodes.Light_garage.material} position={[-8.72, 6.208, 5.418]} scale={0.408} >
        <meshStandardMaterial color='blue' />
      </mesh>
      <mesh geometry={nodes.Light_garden.geometry} material={nodes.Light_garden.material} position={[-0.308, 6.208, 5.418]} scale={0.408} >
      <meshStandardMaterial color='blue' />
    </mesh>
      <mesh geometry={nodes.Light_livingroom.geometry} material={nodes.Light_livingroom.material} position={[-0.308, 6.208, -7.618]} scale={0.408}>
      <meshStandardMaterial color='blue' />
    </mesh>
      <mesh geometry={nodes.Light_bedroom1.geometry} material={nodes.Light_bedroom1.material} position={[-8.761, 6.208, -2.872]} scale={0.408} >
      <meshStandardMaterial color='blue' />
    </mesh>
      <mesh geometry={nodes.Light_bathroom1.geometry} material={nodes.Light_bathroom1.material} position={[-8.761, 6.208, -8.114]} scale={0.408}>
      <meshStandardMaterial color='blue' />
    </mesh> />
      <mesh geometry={nodes.Light2_kitchen.geometry} material={nodes.Light2_kitchen.material} position={[8.754, 6.208, -6.326]} scale={0.408} >
      <meshStandardMaterial color='blue' />
    </mesh>
      <mesh geometry={nodes.Light1_kitchen.geometry} material={nodes.Light1_kitchen.material} position={[8.754, 6.208, 2.574]} scale={0.408} >
      <meshStandardMaterial color='blue' />
    </mesh>
      <mesh geometry={nodes.Fan_livingroom_.geometry} material={nodes.Fan_livingroom_.material} position={[0, 5.246, -4.586]} scale={[0.523, 0.187, 0.523]} />
      <mesh geometry={nodes.Light2_livingroom.geometry} material={nodes.Light2_livingroom.material} position={[-0.308, 6.208, -1.16]} scale={0.408} >
      <meshStandardMaterial color='blue' />
    </mesh>
      <mesh geometry={nodes.Fan_holder_livingroom_.geometry} material={nodes.Fan_holder_livingroom_.material} position={[0, 5.246, -4.586]} scale={[0.523, 0.187, 0.523]} />
      <group scale={[12.184, 12.184, 9.722]}>
        <mesh geometry={nodes.Plane007.geometry} material={nodes.Plane007.material} >
        <meshStandardMaterial color='orange' />
      </mesh> 
        <mesh geometry={nodes.Plane007_1.geometry} material={nodes.Plane007_1.material} >
        <meshStandardMaterial color='orange' />
      </mesh> 
        <mesh geometry={nodes.Plane007_2.geometry} material={nodes.Plane007_2.material} >
        <meshStandardMaterial color='orange' />
      </mesh> 
        <mesh geometry={nodes.Plane007_3.geometry} material={nodes.Plane007_3.material} >
        <meshStandardMaterial color='orange' />
      </mesh> 
      </group>
      <group position={[0, 7.19, 0]}>
        <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} >
        <meshStandardMaterial color='brown' />
      </mesh> 
        <mesh geometry={nodes.Plane008_1.geometry} material={nodes.Plane008_1.material} >
        <meshStandardMaterial color='brown' />
      </mesh> 
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-10.941, 3.597, 7.797]} scale={[0.405, 3.643, 0.405]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-5.954, 3.597, 7.797]} scale={[0.405, 3.643, 0.405]} />
      <group position={[0, 8.122, 0]}>
        <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} >
        <meshStandardMaterial color='orange' />
      </mesh> 
        <mesh geometry={nodes.Plane010_1.geometry} material={nodes.Plane010_1.material} />
      </group>
      <mesh geometry={nodes.Light_officeroom.geometry} material={nodes.Light_officeroom.material} position={[-8.72, 14.304, 5.418]} scale={0.408} >
        <meshStandardMaterial color='blue'  />
      </mesh> 
      <mesh geometry={nodes.Light_bedroom2.geometry} material={nodes.Light_bedroom2.material} position={[-8.72, 14.304, -4.265]} scale={0.408} >
        <meshStandardMaterial color='blue' />
      </mesh>
      <mesh geometry={nodes.Light_livingarea2.geometry} material={nodes.Light_livingarea2.material} position={[-0.255, 14.304, -4.265]} scale={0.408} >
        <meshStandardMaterial color='blue' />
      </mesh>
      <mesh geometry={nodes.Light_storeroom.geometry} material={nodes.Light_storeroom.material} position={[8.648, 14.304, -6.983]} scale={0.408} >
        <meshStandardMaterial color='blue' />
      </mesh>
      <mesh geometry={nodes.Light_bedroom3.geometry} material={nodes.Light_bedroom3.material} position={[8.648, 14.304, 2.045]} scale={0.408} >
        <meshStandardMaterial color='blue' />
      </mesh>
      <mesh geometry={nodes.Front_glass.geometry} material={nodes.Front_glass.material} position={[0.313, 10.154, 0.9]} scale={[2.783, 2.564, 0.098]} >
        <meshPhysicalMaterial 
        color="skyblue"
        transparent={true}
        opacity={0.5} // You can adjust the opacity to control the level of transparency
        roughness={0.1} // Adjust the roughness as needed
        metalness={0.0} // Set to 0 for non-metallic appearance
        />
      </mesh> 
      <mesh geometry={nodes.Roof.geometry} material={nodes.Roof.material} position={[-0.031, 15.359, -0.026]} scale={[12.155, 0.136, 9.663]} >
        <meshStandardMaterial color="#6a6d6d" />
      </mesh> 
    </group>
  )
}

useGLTF.preload('/Home_Panorama.glb')
