/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.glb
*/
// this is imported model

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshBasicMaterial } from 'three';
const material = new MeshBasicMaterial({ color: 'yellow' });

export default function Model(props) {
  const [color, setColor] = useState('red');

  const handleClick = () => {
    if(color=='red'){
      setColor('blue')
    } else{
      setColor("red")
    }
  };
  const ref = useRef()
  const { nodes, materials } = useGLTF('/model.glb')
  const partMesh = nodes['Light'];
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Walls.geometry} material={nodes.Walls.material} >
      <meshStandardMaterial color={'orange'} />
      </mesh>
      {/* <mesh   geometry={nodes.Light.geometry} >
        <meshStandardMaterial color={color} />
        </mesh> > */}
      <mesh geometry={nodes.Floor.geometry} material={nodes.Floor.material} position={[4.69, 0.06, -4.59]} scale={11.04}>
        <meshStandardMaterial color='brown' />
      </mesh> 
      <mesh onClick={handleClick}  position={[7.5 ,10,-5]}>
        <sphereGeometry args={[1, 32, 32]}/>
        <meshStandardMaterial  color={color} />
      </mesh>
      {/* <mesh position={[2.5 ,10,-5]}>
        <cylinderGeometry args={[1, 1, 0.2 ]}  />
      </mesh> */}
      
    </group>
  )
}
